package raidenhttp.utils;

public final class Retcodes {
    public static final int AUTHORIZATION_USER_FAILED_ERROR_VALUE = 1002;
    public static final int INVALID_REQUEST_ERROR_VALUE = 400;
    public static final int PARAMETER_SIGNATURE_INCORRECT_ERROR_VALUE = 127;
    public static final int WRONG_PAYMENT_METHOD_ERROR_VALUE = 126;
    public static final int ACCOUNT_SAFETY_LOGIN_AGAIN_ERROR_VALUE = 115;
    public static final int GAME_BIZ_MISSION_ERROR_VALUE = 100;
    public static final int NO_CONFIG_FOUND_ERROR_VALUE = 7;
    public static final int NO_LAUNCHER_CONFIG_FOUND_ERROR_VALUE = 6;
    public static final int INVALID_RETCODE_MODULE_ERROR_VALUE = 4;
    public static final int RETCODE_SUCCESS = 0;
    public static final int RETCODE_FAILED = -1;
    public static final int RETCODE_CANCEL = -2;
    public static final int MISSING_PARAMETERS_REQUEST_FAILED_ERROR_VALUE = -3;
    public static final int RETCODE_NO_SUCH_METHOD_ERROR_CODE = -10;
    public static final int AUTHORIZATION_FAILED_ERROR_VALUE = -100;
    public static final int SYSTEM_ERROR_VALUE = -101;
    public static final int APP_ID_NOT_FOUND_ERROR_VALUE = -102;
    public static final int GRANT_DEVICE_PARAMETER_ERROR_VALUE = -102;
    public static final int PARAMETER_ERROR_VALUE = -103;
    public static final int GRANT_DEVICE_INVALID_VERIFICATION_CODE_ERROR_VALUE = -104;
    public static final int ACCOUNT_ERROR_VALUE = -105;
    public static final int PROTOCOL_FAILED_ERROR_VALUE = -106;
    public static final int PHONE_NUMBER_NOT_PROVIDED_ERROR_VALUE = -106;
    public static final int THE_REQUEST_FAILED_NETWORK_AT_RISK_ERROR_VALUE = -115;
    public static final int REAL_NAME_REQUIRED_ERROR_VALUE = -118;
    public static final int GUARDIAN_REQUIRED_ERROR_VALUE = -119;
    public static final int ACCOUNT_TOKEN_FAILED_ERROR_VALUE = -201;
    public static final int GRANT_DEVICE_SYSTEM_ERROR_VALUE = -201;
    public static final int ACCOUNT_LOGIN_PASSWORD_DECRYPTION_FAILED_ERROR_VALUE = -215;
    public static final int ACCOUNT_INVALID_FAILED_ERROR_VALUE = -216;
    public static final int REACTIVATE_ACCOUNT_FAILED_ERROR_VALUE = -276;
    public static final int GET_USER_INFORMATION_FAILED_ERROR_VALUE = -502;
    public static final int UNKNOWN_ERROR_VALUE = -503;
    public static final int EOS_DLL_ERROR_VALUE = -1001;
    public static final int EOS_TOKEN_ERROR_VALUE = -1002;
    public static final int GOOGLE_PC_TOKEN_ERROR_VALUE = -1003;
    public static final int INVALID_SUBMITTED_PARAMETERS_ERROR_VALUE = -1003;
    public static final int LAUNCHER_ID_NOT_FOUND_ERROR_VALUE = -1200;
    public static final int LAUNCHER_AGREEMENT_NOT_FOUND_ERROR_VALUE = -1400;
    public static final int ANDROID_PARAMETER_INVALID_ERROR_VALUE = -3001;
    public static final int LAUNCHER_UNKNOWN_ERROR_VALUE = -110001;
    public static final int INVALID_AUTHENTICATOR_ERROR_VALUE = -10010003;
}
